"""added Phone NUmber column in Users table

Revision ID: defd9996b13d
Revises: 921ca9327fa5
Create Date: 2022-01-21 07:44:22.383498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defd9996b13d'
down_revision = '921ca9327fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Phone_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Phone_number')
    op.alter_column('partner', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
